/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Libros;
import Negocio.NegocioLibros;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author user
 */
public class InterfazLibros extends javax.swing.JFrame {
String nombreImagen="";
    public InterfazLibros() {
        initComponents();
         
        this.setResizable(false);
   //     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(2);
        btnAgregar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(true);
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        btnCargarImagen = new javax.swing.JButton();
        lbImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoRegistro = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreAutor = new javax.swing.JTextField();
        txtClaveAutor = new javax.swing.JTextField();
        btnBuscarProv = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        txtClave = new javax.swing.JFormattedTextField();
        txtBarras = new javax.swing.JFormattedTextField();
        txtStock = new javax.swing.JFormattedTextField();
        txtNopags = new javax.swing.JFormattedTextField();
        panelBotones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setToolTipText("Ingrese el Titulo");
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 380, -1));

        btnCargarImagen.setText("Cargar Imagen");
        btnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenActionPerformed(evt);
            }
        });
        jPanel2.add(btnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        lbImagen.setBackground(new java.awt.Color(255, 255, 255));
        lbImagen.setOpaque(true);
        jPanel2.add(lbImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 250, 180));

        jLabel3.setText("Código Barras");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 20));

        jLabel5.setText("Titulo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jLabel6.setText("Stock");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel7.setText("No. Paginas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel9.setText("Código");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Fecha Ingreso");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel10.setText("No.Registro");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        txtNoRegistro.setToolTipText("Ingrese El Numero de Registro");
        txtNoRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoRegistroKeyTyped(evt);
            }
        });
        jPanel3.add(txtNoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));

        txtFecha.setToolTipText("Seleccioe la Fecha de Ingreso");
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 350, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Clave");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel12.setText("Autor");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtNombreAutor.setToolTipText("Ingrese el Nombre del Autor");
        txtNombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAutorKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombreAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, -1));

        txtClaveAutor.setToolTipText("Ingrese la Clave del Autor");
        txtClaveAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveAutorKeyTyped(evt);
            }
        });
        jPanel4.add(txtClaveAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, -1));

        btnBuscarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProvActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 350, 120));

        btnNuevo.setBackground(new java.awt.Color(255, 255, 204));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 130, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 204));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Canasta.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, 60));
        jPanel2.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 230, 170));

        try {
            txtClave.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtClave.setToolTipText("Ingrese el Codigo del Libro");
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        jPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));

        try {
            txtBarras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBarras.setToolTipText("Ingrese el Codigo de Barras");
        txtBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBarrasKeyTyped(evt);
            }
        });
        jPanel2.add(txtBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 170, -1));

        try {
            txtStock.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtStock.setToolTipText("Ingrese ek Stock");
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));

        try {
            txtNopags.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNopags.setToolTipText("Ingrese El Numero de Paginas");
        txtNopags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNopagsKeyTyped(evt);
            }
        });
        jPanel2.add(txtNopags, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 890, 330));

        panelBotones.setBackground(new java.awt.Color(204, 204, 204));
        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, 250));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatos.setInheritsPopupMenu(true);
        TablaDatos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 890, 230));

        btnSalir.setBackground(new java.awt.Color(204, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 710, 130, 70));

        btnModificar.setBackground(new java.awt.Color(204, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, 140, 70));

        btnEliminar.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Borrar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 140, 70));

        jLabel13.setBackground(new java.awt.Color(255, 255, 204));
        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Libros");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 960, 80));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 730, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenActionPerformed
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("JPG & PNG Imagenes","jpg","png");
        JFileChooser fileChooser= new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setFileFilter(filtro);
        fileChooser.setDialogTitle("Abrir Archivo");
        File ruta=new File("\"C:\\ImagenesPapeleria\"");
        fileChooser.setCurrentDirectory(ruta);
        int resultado=fileChooser.showOpenDialog(this);
        if(resultado!=JFileChooser.CANCEL_OPTION){
            File nombreArchivo=fileChooser.getSelectedFile();
            nombreImagen=String.valueOf(nombreArchivo);
            Image foto=getToolkit().getImage(nombreImagen);
            foto=foto.getScaledInstance(lbImagen.getWidth(), lbImagen.getHeight(),Image.SCALE_DEFAULT);
            lbImagen.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnCargarImagenActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(verificar()){
        Libros libro = new Libros();
        libro.setClave(Integer.parseInt(txtClave.getText()));
        libro.setTitulo((txtTitulo.getText()));
        libro.setStock(Integer.parseInt(txtStock.getText()));
        libro.setNPags((txtNopags.getText()));
        libro.setNopedido(Integer.parseInt(txtNoRegistro.getText()));
        libro.setClaveAutor(Integer.parseInt(txtClaveAutor.getText()));
        
        libro.setImagen(nombreImagen);
        libro.setRutaImagen(nombreImagen);
        
        Date fecha=txtFecha.getDate();
        long d=fecha.getTime();
        java.sql.Date solofecha=new java.sql.Date(d);
        libro.setFecha_Ingreso(solofecha);
        libro.setCodBarras(txtBarras.getText());
        new NegocioLibros().PuenteRegistroNvo(libro);
        Limpiar();
        LlenarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if(verificar()){
          int n=JOptionPane.showConfirmDialog(null,"¿Seguro que deseas eliminar? ");
          if(n==0){
              Libros libro = new Libros();
        libro.setClave(Integer.parseInt(txtClave.getText()));
              try {
                  new NegocioLibros().PuenteEliminar(libro);
              } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Error "+ex,"Verificar",JOptionPane.INFORMATION_MESSAGE);
              }
        Limpiar();
        LlenarTabla();
          }
      }  
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(verificar()){
        Libros libro = new Libros();
       libro.setClave(Integer.parseInt(txtClave.getText()));
        libro.setTitulo((txtTitulo.getText()));
        libro.setStock(Integer.parseInt(txtStock.getText()));
        libro.setNPags((txtNopags.getText()));
        libro.setNopedido(Integer.parseInt(txtNoRegistro.getText()));
        libro.setClaveAutor(Integer.parseInt(txtClaveAutor.getText()));
        
        libro.setImagen(nombreImagen);
        libro.setRutaImagen(nombreImagen);
        
        Date fecha=txtFecha.getDate();
        long d=fecha.getTime();
        java.sql.Date solofecha=new java.sql.Date(d);
        libro.setFecha_Ingreso(solofecha);
        libro.setCodBarras(txtBarras.getText());
        try{
        new NegocioLibros().PuenteActualizar(libro);
        } catch (SQLException ex){
           JOptionPane.showMessageDialog(null,"Error "+ex,"Verificar",JOptionPane.INFORMATION_MESSAGE);
        }
        Limpiar();
        LlenarTabla();
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProvActionPerformed
       BuscarAutor bp=new BuscarAutor(txtClaveAutor, txtNombreAutor);
       bp.setVisible(true);
       txtClaveAutor.setText(bp.clavep.getText());
       txtNombreAutor.setText(bp.nombrep.getText());
    }//GEN-LAST:event_btnBuscarProvActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       txtClave.setEnabled(true);
        btnAgregar.setEnabled(true);
       Limpiar();
       txtClave.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
      if (evt.getButton() == 1) {
            txtClave.setEnabled(false);
            int fila = TablaDatos.getSelectedRow();

          
            String fe = TablaDatos.getValueAt(fila, 5).toString();
            DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date fecha = formato.parse(fe);
                txtFecha.setDate(fecha);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }
       

            txtClave.setText(TablaDatos.getValueAt(fila, 0).toString());
            txtTitulo.setText(TablaDatos.getValueAt(fila, 1).toString());
            txtStock.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtNopags.setText(TablaDatos.getValueAt(fila, 3).toString());

            txtNoRegistro.setText(TablaDatos.getValueAt(fila, 4).toString());
            txtBarras.setText(TablaDatos.getValueAt(fila, 5).toString());
            txtClaveAutor.setText(TablaDatos.getValueAt(fila, 7).toString());
            nombreImagen = TablaDatos.getValueAt(fila, 6).toString();

            int clv = Integer.parseInt(txtClave.getText());
            ImageIcon img = new NegocioLibros().puenteObtenerImagen(clv);
            Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbImagen.getWidth(), lbImagen.getHeight(), Image.SCALE_DEFAULT));
            if (img != null) {
                lbImagen.setIcon(icono);
            }

            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnAgregar.setEnabled(false);
 
      
     }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtClave.getText().trim().length()==11){
            evt.consume();
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarrasKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtBarras.getText().trim().length()==15){
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtBarrasKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtStock.getText().trim().length()==11){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtNopagsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopagsKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtNopags.getText().trim().length()==10){
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopagsKeyTyped

    private void txtNoRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRegistroKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtNoRegistro.getText().trim().length()==10){
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRegistroKeyTyped

    private void txtClaveAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveAutorKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtClaveAutor.getText().trim().length()==10){
            evt.consume();        }// TODO add your handling code here:
    }//GEN-LAST:event_txtClaveAutorKeyTyped

    private void txtNombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAutorKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtNombreAutor.getText().trim().length()==11){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutorKeyTyped

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
        try {
  Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tblibros where clave =?");
        pst.setString(1,txtClave.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtClave.setText(rs.getString("clave"));
        txtTitulo.setText(rs.getString("titulo"));
        txtStock.setText(rs.getString("stock"));
        txtBarras.setText(rs.getString("codigobarras"));
        txtNopags.setText(rs.getString("npaginas"));
        }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyPressed
void Limpiar(){
    txtClave.setText("");
    txtTitulo.setText("");
    txtBarras.setText("");
    txtStock.setText("");
    txtNopags.setText("");
    lbImagen.setIcon(null);
    txtNoRegistro.setText("");
    txtFecha.setDate(null);
    txtClaveAutor.setText("");
    txtNombreAutor.setText("");
}
boolean verificar(){
    boolean v;
    if(txtClave.getText().isEmpty() || txtTitulo.getText().isEmpty() || txtBarras.getText().isEmpty() || txtStock.getText().isEmpty() || txtNopags.getText().isEmpty()
            || lbImagen.getIcon()== null || txtNoRegistro.getText().isEmpty() || txtFecha.getDate()==null|| txtClaveAutor.getText().isEmpty() || txtNombreAutor.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Llenar todos los datos", "Falta de datos",JOptionPane.INFORMATION_MESSAGE);
        v=false;
    }else
        v=true;
return v;

}
public void LlenarTabla(){
    try{
        NegocioLibros tbl=new NegocioLibros();
        tbl.PuenteMostrarTabla(TablaDatos);
                
    }catch (Exception e){
        
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProv;
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JFormattedTextField txtBarras;
    private javax.swing.JFormattedTextField txtClave;
    private javax.swing.JTextField txtClaveAutor;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtNoRegistro;
    private javax.swing.JTextField txtNombreAutor;
    private javax.swing.JFormattedTextField txtNopags;
    private javax.swing.JFormattedTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
