/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Clientes;
import Negocio.NegocioClientes;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class InterfazClientes extends javax.swing.JFrame {
NegocioClientes nc;
 ArrayList<Clientes> lista = null;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Clientes
     */
    public InterfazClientes() {
        initComponents();
         this.setSize(850, 700);
        this.setResizable(false);
        this.setLocationRelativeTo(this);
       btnAgregar.setEnabled(true);
        btnEliminar1.setEnabled(false);
        btnModificar.setEnabled(false);
        LlenarTabla();
items();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbocliente = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setTitle("Clientes Directorio");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 705));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setText("Teléfono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        txtNom.setToolTipText("Ingrese nombre completo del cliente");
        txtNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomMouseClicked(evt);
            }
        });
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 410, 30));

        txtEmail.setToolTipText("Ingrese email (ej. @gmail.com, @hotmail.com, etc) del cliente");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 410, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.setMnemonic('a');
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Clic para ingesar datos a la tabla o alt+a");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 60));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setMnemonic('m');
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Clic para modificar datos de la fila seleccionada o alt+m");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 140, 60));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 60));

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnEliminar1.setMnemonic('e');
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setToolTipText("Clic para eliminar fila seleccionada o alt+e");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 140, 60));

        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        txtDi.setToolTipText("Ingrese dirección del cliente");
        jPanel1.add(txtDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 410, 30));

        jLabel7.setText("DNI:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtDNI.setToolTipText("Ingrese DNI del cliente");
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 210, 30));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setMnemonic('s');
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Dar clic para salir o alt+s");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 110, 60));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Clientes ");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbocliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbocliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboclienteFocusGained(evt);
            }
        });
        cbocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboclienteActionPerformed(evt);
            }
        });
        jPanel2.add(cbocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 260, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 140, -1));

        txtCod.setToolTipText("Ingrese el codigo de cliente");
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel2.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 30));

        txtTel.setToolTipText("Ingrese numero de telefono");
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 410, 30));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, 50));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-user-48.png"))); // NOI18N
        jPanel2.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -20, 170, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 820, 250));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatos.setInheritsPopupMenu(true);
        TablaDatos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 820, 200));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void items(){
    TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtCod);
    try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select idcliente from tbclientes");

    ResultSet rs = pst.executeQuery();
while (rs.next()){
    textAutoCompleter.addItem(rs.getString("idcliente"));
}
   }catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
}        
}

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     if (Verificar()) {

            Clientes clie = new Clientes();
            clie.setIdcliente(Integer.parseInt(txtCod.getText()));
            clie.setNombre(txtNom.getText());
            clie.setDni(txtDNI.getText());
            clie.setTelefono(Long.parseLong(txtTel.getText()));
            clie.setDireccion(txtDi.getText());
            clie.setEmail(txtEmail.getText());

            new NegocioClientes().PuenteRegistroNvo(clie);
            Limpiar();
               LlenarTabla();
            btnAgregar.setEnabled(false);
        }
 
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (Verificar()) {

          Clientes cli = new Clientes();
            cli.setIdcliente(Integer.parseInt(txtCod.getText()));
            cli.setNombre(txtNom.getText());
            cli.setDni(txtDNI.getText());
            cli.setTelefono(Long.parseLong(txtTel.getText()));
            cli.setDireccion(txtDi.getText());
            cli.setEmail(txtEmail.getText());
            

            try {
                new NegocioClientes().PuenteActualizar(cli);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
            }
            Limpiar();
               LlenarTabla();
       

                  
    }          
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
   btnAgregar.setEnabled(true);
        Limpiar();
        txtCod.setEnabled(true);
        txtCod.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
if (Verificar()) {
            int n = JOptionPane.showConfirmDialog(null, "Seguro que deseas eliminar?: ");
            if (n == 0) {
                Clientes cli = new Clientes();
               cli.setIdcliente(Integer.parseInt(txtCod.getText()));
                try {
                    new NegocioClientes().PuenteEliminar(cli);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
                }
                Limpiar();
                   LlenarTabla();
            }
}
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        if(evt.getButton()==1){
            txtCod.setEnabled(false);
            int fila=TablaDatos.getSelectedRow();
            txtCod.setText(TablaDatos.getValueAt(fila, 0).toString());
            txtNom.setText(TablaDatos.getValueAt(fila, 1).toString());
            txtDNI.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtTel.setText(TablaDatos.getValueAt(fila, 3).toString());
            txtDi.setText(TablaDatos.getValueAt(fila, 4).toString());
            txtEmail.setText(TablaDatos.getValueAt(fila, 5).toString());

          
        
            btnEliminar1.setEnabled(true);
            btnModificar.setEnabled(true);
            btnAgregar.setEnabled(false);
        }
    }
     public void LlenarTabla(){
    try{
        NegocioClientes tbl=new NegocioClientes();
        tbl.PuenteMostrarTabla(TablaDatos);
                
    }catch (Exception e){
        
    
}
        
        
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        boolean mayusculas = key>=65 && key<=90;
        boolean minusculas = key>=97 && key<=122;
        
        boolean espacio = key==32;
        
        if(!(minusculas||mayusculas||espacio)){
            
            evt.consume();
            
            
            
        }
    }//GEN-LAST:event_txtNomKeyTyped

    private void cboclienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboclienteFocusGained
        nc = new Negocio.NegocioClientes();
        cbocliente.removeAll();
        lista = nc.consultarComboCarrera();
        for (int i = 0; i < lista.size(); i++) {
            cbocliente.addItem(lista.get(i).getNombre());
        }
        }
        void Limpiar() {
            txtCod.setText("");
            txtNom.setText("");
            txtDNI.setText("");
            txtTel.setText("");
            txtDi.setText("");
            txtEmail.setText("");
        }

        boolean Verificar() {
            boolean v;
            if (txtCod.getText().isEmpty()
                || txtNom.getText().isEmpty()
                || txtDNI.getText().isEmpty()
                || txtTel.getText().isEmpty()
                || txtDi.getText().isEmpty()
                || txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Se deben llenar todos los datos", "Faltan datos", JOptionPane.INFORMATION_MESSAGE);
                v = false;
            } else {
                v = true;
            }
            return v;
    }//GEN-LAST:event_cboclienteFocusGained

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
            boolean numeros = key>=48 && key <=57;
            if(!numeros){
                evt.consume();
            }
            if(txtCod.getText().trim().length()==11){
                evt.consume();
            }
        
    }//GEN-LAST:event_txtCodKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtTel.getText().trim().length()==10){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void cboclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboclienteActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomMouseClicked
        
        try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tbclientes where idcliente =?");
        pst.setString(1,txtCod.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtCod.setText(rs.getString("idcliente"));
        txtNom.setText(rs.getString("nombre"));
        txtDNI.setText(rs.getString("dni"));
        txtTel.setText(rs.getString("telefono"));
        txtDi.setText(rs.getString("direccion"));
        txtEmail.setText(rs.getString("email"));
    }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }

    }//GEN-LAST:event_txtNomMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        txtCod.setText((String)cbocliente.getSelectedItem());
        String id=txtCod.getText();
        try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tbclientes where nombre =?");
        pst.setString(1,txtCod.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtCod.setText(rs.getString("idcliente"));
        txtNom.setText(rs.getString("nombre"));
        txtDNI.setText(rs.getString("dni"));
        txtTel.setText(rs.getString("telefono"));
        txtDi.setText(rs.getString("direccion"));
        txtEmail.setText(rs.getString("email"));
    }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }

    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbocliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
