/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Acceso;
import Negocio.negocioAdministrar;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class InterfazUsuarios extends javax.swing.JFrame {
   negocioAdministrar na;
    ArrayList<Acceso> lista = null;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Proveedores
     */
    public InterfazUsuarios() {
        initComponents();
        
        this.setSize(900, 700);
        this.setResizable(false);
        this.setLocationRelativeTo(this);
         btnAgregar.setEnabled(true);
        btnEliminar1.setEnabled(false);
        btnModificar.setEnabled(false);
        LlenarTabla();
items();
    }
public void items(){
    TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtID);
   
    try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select id from tbacceso");
    ResultSet rs = pst.executeQuery();
while (rs.next()){
    textAutoCompleter.addItem(rs.getString("id"));
}
   }catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
}        
     
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtRango = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        cboProv = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        btnRegresar2 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setTitle("Proveedores Directorio");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel4.setText("Puesto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        txtContraseña.setToolTipText("Ingrese la contraseña");
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 410, 30));

        txtRango.setToolTipText("Ingrese puesto de completo o basico");
        txtRango.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRangoKeyTyped(evt);
            }
        });
        jPanel1.add(txtRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 410, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.setMnemonic('a');
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Clic para ingesar datos a la tabla o alt+a");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, 60));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setMnemonic('m');
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Clic para modificar datos de la fila seleccionada o alt+m");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 130, 60));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 60));

        btnEliminar1.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnEliminar1.setMnemonic('e');
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setToolTipText("Clic para eliminar fila seleccionada o alt+e");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 150, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setMnemonic('s');
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Dar clic para salir o alt+s");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 120, 60));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Usuarios");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        cboProv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboProv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboProvFocusGained(evt);
            }
        });
        jPanel2.add(cboProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 260, -1));

        txtNombre.setToolTipText("Ingrese nombre completo del usuario");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 410, 30));

        btnRegresar2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        txtID.setToolTipText("Ingrese El ID");
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 850, 260));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatos.setInheritsPopupMenu(true);
        TablaDatos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 870, 230));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    
 if (Verificar()) {

            Acceso acc = new Acceso();

            acc.setId(Integer.parseInt(txtID.getText()));
            acc.setNombre(txtNombre.getText());
            acc.setContraseña(txtContraseña.getText());
            acc.setTipo(txtRango.getText());
            new negocioAdministrar().PuenteRegistroNvo(acc);
            Limpiar();
            btnAgregar.setEnabled(false);
             LlenarTabla();
        }
       
    
     
       
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
         if (Verificar()) {
            int n = JOptionPane.showConfirmDialog(null, "Seguro que deseas eliminar?: ");
            if (n == 0) {
                Acceso acc = new Acceso();
                acc.setId(Integer.parseInt(txtID.getText()));
                try {
                    new negocioAdministrar().PuenteEliminar(acc);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
                }
                Limpiar();
                 LlenarTabla();
            }
        }                                          

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (Verificar()) {

            Acceso acc = new Acceso();

            acc.setId(Integer.parseInt(txtID.getText()));
            acc.setNombre(txtNombre.getText());
            acc.setContraseña(txtContraseña.getText());
            acc.setTipo(txtRango.getText());

            try {
                new negocioAdministrar().PuenteActualizar(acc);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
            }
            Limpiar();
             LlenarTabla();
        }

                  
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
         btnAgregar.setEnabled(true);
        Limpiar();
        txtID.setEnabled(true);
        txtID.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        if(evt.getButton()==1){
         txtID.setEnabled(false);
            int fila=TablaDatos.getSelectedRow();
            txtID.setText(TablaDatos.getValueAt(fila, 0).toString());
            txtNombre.setText(TablaDatos.getValueAt(fila, 1).toString());
            txtContraseña.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtRango.setText(TablaDatos.getValueAt(fila, 3).toString());
          
            
            
    
             btnEliminar1.setEnabled(true);
            btnModificar.setEnabled(true);
            btnAgregar.setEnabled(false);
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void cboProvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboProvFocusGained
        na = new negocioAdministrar();
        cboProv.removeAll();
        lista = na.consultarCombo();
        for (int i = 0; i < lista.size(); i++) {
            cboProv.addItem(lista.get(i).getNombre());
        }
    }//GEN-LAST:event_cboProvFocusGained

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
int key = evt.getKeyChar();
        boolean mayusculas = key>=65 && key<=90;
        boolean minusculas = key>=97 && key<=122;
        
        boolean espacio = key==32;
        
        if(!(minusculas||mayusculas||espacio)){
            
            evt.consume();
            
            
            
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtRangoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRangoKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key>=65 && key<=90;
        boolean minusculas = key>=97 && key<=122;
        
        boolean espacio = key==32;
        
        if(!(minusculas||mayusculas||espacio)){
            
            evt.consume();
            
            
            
        }
    }//GEN-LAST:event_txtRangoKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
int key = evt.getKeyChar();
boolean numeros = key>=48 && key <=57;
if(!numeros){
    evt.consume();
}
if(txtID.getText().trim().length()==11){
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tbacceso where id =?");
        pst.setString(1,txtID.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtID.setText(rs.getString("id"));
        txtNombre.setText(rs.getString("nombre"));
        txtContraseña.setText("******");
        txtRango.setText(rs.getString("tipo"));
    }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tbacceso where id =?");
        pst.setString(1,txtID.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtID.setText(rs.getString("id"));
        txtNombre.setText(rs.getString("nombre"));
        txtContraseña.setText("******");
        txtRango.setText(rs.getString("tipo"));
    }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }          // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked
  void Limpiar() {
        txtID.setText("");
        txtNombre.setText("");

        txtContraseña.setText("");
        txtRango   .setText("");
      
    }

    boolean Verificar() {
        boolean v;
        if (txtID.getText().isEmpty()
                || txtNombre.getText().isEmpty()
                || txtContraseña.getText().isEmpty()
                || txtRango.getText().isEmpty())
                {
            JOptionPane.showMessageDialog(null, "Se deben llenar todos los datos", "Faltan datos", JOptionPane.INFORMATION_MESSAGE);
            v = false;
        } else {
            v = true;
        }
        return v;
    }
    public void LlenarTabla(){
    try{
        negocioAdministrar tbl=new negocioAdministrar();
        tbl.PuenteMostrarTabla(TablaDatos);
                
    }catch (Exception e){
        
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRango;
    // End of variables declaration//GEN-END:variables
}
