/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Creditos;
import Datos.MantenimientoCreditos;
import Negocio.NegocioCreditos;
import Negocio.negocioAdministrar;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class InterfazCreditos extends javax.swing.JFrame {
DefaultTableModel modelo = new DefaultTableModel();
 NegocioCreditos nc;
    MantenimientoCreditos mcc;
 ArrayList<Creditos> lista = null;

    public InterfazCreditos() {
        initComponents();
          this.setResizable(false);
          this.setLocationRelativeTo(this);
         btnAgregar.setEnabled(true);
        btnEliminar1.setEnabled(false);
        btnModificar.setEnabled(false);
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcredito = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtFolio = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtclie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCli = new javax.swing.JButton();
        txtDinero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Créditos");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 640, 440));

        jLabel3.setText("Folio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel4.setText("Id Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtcredito.setToolTipText("Ingrese código de identificación");
        jPanel1.add(txtcredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 130, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.setMnemonic('a');
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Clic para ingesar datos a la tabla o alt+a");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 150, 60));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setMnemonic('m');
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Clic para modificar datos de la fila seleccionada o alt+m");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 150, 60));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 150, 60));

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnEliminar1.setMnemonic('e');
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setToolTipText("Clic para eliminar fila seleccionada o alt+e");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 150, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setMnemonic('s');
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Dar clic para salir o alt+s");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 563, 150, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Créditos");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 80));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 770, -1, -1));
        jPanel1.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 30));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclieActionPerformed(evt);
            }
        });
        jPanel2.add(txtclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 410, 30));

        jLabel1.setText("Id Cliente:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        txtDinero.setToolTipText("Monto total a deber, sumar o restar movimentos");
        jPanel2.add(txtDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 150, 50));

        jLabel7.setText("Monto:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));
        jPanel2.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 360, 30));

        jLabel6.setText("Nombre del Cliente:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 650, 240));

        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void generarNumeroid() {
        int folio = mcc.numSerieVentas();
        if (folio == 0) {
            txtcredito.setText("0000001");
        } else {
            int incremento = folio;
            incremento = incremento + 1;
            txtcredito.setText("00000" + incremento);
       
    }
 }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
if (Verificar()) {

            Creditos cre= new Creditos();

            cre.setIdcredito(Integer.parseInt(txtcredito.getText()));
            cre.setFolio(Integer.parseInt(txtFolio.getText()));
            cre.setIdcliente(Integer.parseInt(txtclie.getText()));
            cre.setId(Integer.parseInt(txtID.getText()));
            cre.setMonto(Float.parseFloat(txtDinero.getText()));

            new NegocioCreditos().PuenteRegistroNvo(cre);
            Limpiar();
            btnAgregar.setEnabled(false);
             LlenarTabla();
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       if (Verificar()) {

            Creditos cre= new Creditos();

            cre.setIdcredito(Integer.parseInt(txtcredito.getText()));
            cre.setFolio(Integer.parseInt(txtFolio.getText()));
            cre.setIdcliente(Integer.parseInt(txtclie.getText()));
            cre.setId(Integer.parseInt(txtID.getText()));
            cre.setMonto(Float.parseFloat(txtDinero.getText()));

            try {
                new NegocioCreditos().PuenteActualizar(cre);
         
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
            }
            Limpiar();
             LlenarTabla();
        }

                  
    
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
          btnAgregar.setEnabled(true);
        Limpiar();
        txtcredito.setEnabled(true);
        txtcredito.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
           if (Verificar()) {
            int n = JOptionPane.showConfirmDialog(null, "Seguro que deseas eliminar?: ");
            if (n == 0) {
               Creditos cre= new Creditos();
               cre.setIdcredito(Integer.parseInt(txtcredito.getText()));
                try {
                    new NegocioCreditos().PuenteEliminar(cre);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
                }
                Limpiar();
            LlenarTabla();
        }                                          
           }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }
    void Limpiar() {
        txtDinero.setText("");
        txtclie.setText("");
        txtFolio.setText("");
        txtID.setText("");
        txtcredito   .setText("");
        
    }

    boolean Verificar() {
        boolean v;
        if (txtcredito.getText().isEmpty()
                || txtFolio.getText().isEmpty()
                || txtDinero.getText().isEmpty()
                || txtID.getText().isEmpty()
                || txtclie.getText().isEmpty())
               {
            JOptionPane.showMessageDialog(null, "Se deben llenar todos los datos", "Faltan datos", JOptionPane.INFORMATION_MESSAGE);
            v = false;
        } else {
            v = true;
        
        }
        
        return v;
    }
    public void LlenarTabla(){
    try{
        NegocioCreditos tbl=new NegocioCreditos();
        tbl.PuenteMostrarTabla(TablaDatos);
                
    }catch (Exception e){
        
    
}
    }//GEN-LAST:event_btnSalirActionPerformed
   
    
    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        BuscarClientes bp=new BuscarClientes(txtclie, txtNom);
        bp.setVisible(true);
        txtclie.setText(bp.idcliente.getText());
        txtNom.setText(bp.nombrec.getText());
    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclieActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
         if(evt.getButton()==1){
            txtcredito.setEnabled(false);
            int fila=TablaDatos.getSelectedRow();
            txtclie.setText(TablaDatos.getValueAt(fila, 0).toString());
            txtFolio.setText(TablaDatos.getValueAt(fila, 1).toString());
            txtDinero.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtcredito.setText(TablaDatos.getValueAt(fila, 3).toString());
            txtID.setText(TablaDatos.getValueAt(fila, 4).toString());
        
        
           btnEliminar1.setEnabled(true);
            btnModificar.setEnabled(true);
            btnAgregar.setEnabled(false);
         }
    }//GEN-LAST:event_TablaDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtclie;
    private javax.swing.JTextField txtcredito;
    // End of variables declaration//GEN-END:variables
}
