/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Autores;
import Negocio.NegocioAutor;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class InterfazAutor extends javax.swing.JFrame {
   NegocioAutor np;
    ArrayList<Autores> lista = null;
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Proveedores
     */
    public InterfazAutor() {
        initComponents();
        
       // this.setSize(850, 750);
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        btnAgregar.setEnabled(true);
        btnEliminar1.setEnabled(false);
        btnModificar.setEnabled(false);
        LlenarTabla();
items();
items2();
    }
public void items(){
    TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtClave);
    try {
                Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select claveautor from tbautor");

    ResultSet rs = pst.executeQuery();
while (rs.next()){
    textAutoCompleter.addItem(rs.getString("claveautor"));
}
   }catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
}        
}
public void items2(){
    TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtNomPro);
    try {
                Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select nombre from tbautor");

    ResultSet rs = pst.executeQuery();
while (rs.next()){
    textAutoCompleter.addItem(rs.getString("nombre"));
}
   }catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
}        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDPro = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtTelPro = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtNomPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setTitle("Proveedores Directorio");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        txtDPro.setToolTipText("Ingrese dirección del autor");
        jPanel1.add(txtDPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 410, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.setMnemonic('a');
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Clic para ingesar datos a la tabla o alt+a");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, 60));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setMnemonic('m');
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Clic para modificar datos de la fila seleccionada o alt+m");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 130, 60));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 130, 60));

        btnEliminar1.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnEliminar1.setMnemonic('e');
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setToolTipText("Clic para eliminar fila seleccionada o alt+e");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 150, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setMnemonic('s');
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Dar clic para salir o alt+s");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 120, 60));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AUTORES");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setToolTipText("Ingrese Correo");
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 410, 30));

        jLabel8.setText("Correo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autor2.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 55));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 55));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 100));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        txtTelPro.setToolTipText("Ingrese numero de telefono");
        txtTelPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelProKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 190, 30));

        txtClave.setToolTipText("Ingrese clave del autor");
        txtClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClaveMouseClicked(evt);
            }
        });
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        jPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, 30));

        txtNomPro.setToolTipText("Ingrese nombre completo del autor");
        txtNomPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomProMouseClicked(evt);
            }
        });
        txtNomPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProKeyTyped(evt);
            }
        });
        jPanel2.add(txtNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 410, 30));

        jLabel6.setText("Clave:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setText("Teléfono:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel2.setText("RFC:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtRFC.setToolTipText("Ingrese el RFC del autor");
        jPanel2.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 410, 30));

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 850, 280));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatos.setInheritsPopupMenu(true);
        TablaDatos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 820, 130));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      
 if (Verificar()) {

            Autores prov = new Autores();

            prov.setClaveautor(Integer.parseInt(txtClave.getText()));
            prov.setNombre(txtNomPro.getText());
            prov.setRfc(txtRFC.getText());
            prov.setTelefono(Long.parseLong(txtTelPro.getText()));
            prov.setDireccion(txtDPro.getText());
            prov.setCorreo(txtCorreo.getText());

            new NegocioAutor().PuenteRegistroNvo(prov);
            Limpiar();
             LlenarTabla();
            btnAgregar.setEnabled(false);
        }
        
    
     
       
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
         if (Verificar()) {
            int n = JOptionPane.showConfirmDialog(null, "Seguro que deseas eliminar?: ");
            if (n == 0) {
                Autores prov = new Autores();
                prov.setClaveautor(Integer.parseInt(txtClave.getText()));
                try {
                    new NegocioAutor().PuenteEliminar(prov);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
                }
                Limpiar();
                 LlenarTabla();
            }
        }                                          

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (Verificar()) {

            Autores prov = new Autores();

            prov.setClaveautor(Integer.parseInt(txtClave.getText()));
            prov.setNombre(txtNomPro.getText());
            prov.setRfc(txtRFC.getText());
            prov.setTelefono(Long.parseLong(txtTelPro.getText()));
            prov.setDireccion(txtDPro.getText());
            prov.setCorreo(txtCorreo.getText());

            try {
                new NegocioAutor().PuenteActualizar(prov);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex, "Verificacion", JOptionPane.ERROR_MESSAGE);
            }
            Limpiar();
             LlenarTabla();
        }

                  
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
         btnAgregar.setEnabled(true);
        Limpiar();
        txtClave.setEnabled(true);
        txtClave.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
          if(evt.getButton()==1){
            txtClave.setEnabled(false);
            int fila=TablaDatos.getSelectedRow();
            txtClave.setText(TablaDatos.getValueAt(fila, 0).toString());
            txtNomPro.setText(TablaDatos.getValueAt(fila, 1).toString());
            txtRFC.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtTelPro.setText(TablaDatos.getValueAt(fila, 3).toString());
            txtDPro.setText(TablaDatos.getValueAt(fila, 4).toString());
            txtCorreo.setText(TablaDatos.getValueAt(fila, 5).toString());

          

             btnEliminar1.setEnabled(true);
            btnModificar.setEnabled(true);
            btnAgregar.setEnabled(false);
        }
        }
        public void LlenarTabla(){
              try{
        NegocioAutor tbl=new NegocioAutor();
        tbl.PuenteMostrarTabla(TablaDatos);
                
    }catch (Exception e){
    
    }

    }//GEN-LAST:event_TablaDatosMouseClicked

    private void txtNomProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean mayusculas = key>=65 && key<=90;
        boolean minusculas = key>=97 && key<=122;
        
        boolean espacio = key==32;
        
        if(!(minusculas||mayusculas||espacio)){
            
            evt.consume();   
        }        
    }//GEN-LAST:event_txtNomProKeyTyped

    private void txtTelProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelProKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtTelPro.getText().trim().length()==10){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtTelProKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        if(txtClave.getText().trim().length()==11){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveMouseClicked
        
    }//GEN-LAST:event_txtClaveMouseClicked

    private void txtNomProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomProMouseClicked
        try {
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca","root","");
        PreparedStatement pst = conexion.prepareStatement("select * from tbautor where claveautor =?");
        pst.setString(1,txtClave.getText().trim());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        txtClave.setText(rs.getString("claveautor"));
        txtNomPro.setText(rs.getString("nombre"));
        txtRFC.setText(rs.getString("rfc"));
        txtTelPro.setText(rs.getString("telefono"));
        txtDPro.setText(rs.getString("direccion"));
        txtCorreo.setText(rs.getString("correo"));
    }else{
        JOptionPane.showMessageDialog(null, "Autor No Registrado");
    }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProMouseClicked
  void Limpiar() {
        txtClave.setText("");
        txtNomPro.setText("");
        txtRFC.setText("");
        txtTelPro.setText("");
        txtDPro   .setText("");
        txtCorreo.setText("");
    }

    boolean Verificar() {
        boolean v;
        if (txtClave.getText().isEmpty()
                || txtNomPro.getText().isEmpty()
                || txtRFC.getText().isEmpty()
                || txtTelPro.getText().isEmpty()
                || txtDPro.getText().isEmpty()
                || txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Se deben llenar todos los datos", "Faltan datos", JOptionPane.INFORMATION_MESSAGE);
            v = false;
        } else {
            v = true;
        }
        return v;
    }


  



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDPro;
    private javax.swing.JTextField txtNomPro;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelPro;
    // End of variables declaration//GEN-END:variables
}
