/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Datos.Acceso;
import javax.swing.JFrame;
import com.imagen.ClaseImagen;
/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {
public static Acceso usu;

    ClaseImagen img=new ClaseImagen();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
      
    }

    public Principal(Acceso usu) {
        
        initComponents();
         img.AjustarImagenL(lbLogo, "Imagenes", "logo", "png");
       Principal.usu= usu;
  this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (!usu.getTipo().equals("completo")) {
            menuArchivo.setEnabled(true);
            menuVenta.setEnabled(true); 
            menuProveedores.setEnabled(false);
            menuClientes.setEnabled(false);
            menuReportes.setEnabled(false);
            menuMantenimiento.setEnabled(false);
        } else {
            menuArchivo.setEnabled(true);
            menuVenta.setEnabled(true); 
            menuProveedores.setEnabled(true);
            menuClientes.setEnabled(true);
            menuReportes.setEnabled(true);
            menuMantenimiento.setEnabled(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itSalir = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        itCaja = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        itDirePro = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        itDireClie = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itRegis = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        itmProductos = new javax.swing.JMenuItem();
        itUsuarios = new javax.swing.JMenuItem();
        itDevoluciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Ventana.setBackground(new java.awt.Color(204, 255, 204));
        Ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Ventana.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 690));

        getContentPane().add(Ventana, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        menuArchivo.setMnemonic('a');
        menuArchivo.setText("Archivo");
        menuArchivo.setToolTipText("Clic para abrir herramientas de archivo o alt+a");
        menuArchivo.setEnabled(false);

        itSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itSalir.setMnemonic('C');
        itSalir.setText("Salir");
        itSalir.setToolTipText("");
        itSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itSalir);

        jMenuBar1.add(menuArchivo);

        menuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro.png"))); // NOI18N
        menuVenta.setMnemonic('n');
        menuVenta.setText("Prestamos");
        menuVenta.setToolTipText("Clic para abrir herramientas de ventas o alt+n");
        menuVenta.setEnabled(false);
        menuVenta.setMaximumSize(new java.awt.Dimension(150, 32767));
        menuVenta.setPreferredSize(new java.awt.Dimension(60, 48));

        itCaja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itCaja.setText("Prestamos");
        itCaja.setToolTipText("");
        itCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCajaActionPerformed(evt);
            }
        });
        menuVenta.add(itCaja);

        jMenuBar1.add(menuVenta);

        menuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autor.png"))); // NOI18N
        menuProveedores.setMnemonic('p');
        menuProveedores.setText("Autores");
        menuProveedores.setToolTipText("Clic para abrir herramientas de proveedores o alt+p");
        menuProveedores.setEnabled(false);

        itDirePro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itDirePro.setText("Directorio");
        itDirePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itDireProActionPerformed(evt);
            }
        });
        menuProveedores.add(itDirePro);

        jMenuBar1.add(menuProveedores);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-user-48.png"))); // NOI18N
        menuClientes.setMnemonic('u');
        menuClientes.setText("Clientes");
        menuClientes.setToolTipText("Clic para abrir herramientas de clientes o alt+u");
        menuClientes.setContentAreaFilled(false);
        menuClientes.setEnabled(false);

        itDireClie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itDireClie.setText("Directorio");
        itDireClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itDireClieActionPerformed(evt);
            }
        });
        menuClientes.add(itDireClie);

        jMenuBar1.add(menuClientes);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/training_48px.png"))); // NOI18N
        menuReportes.setMnemonic('t');
        menuReportes.setText("Reportes");
        menuReportes.setToolTipText("Clic para abrir herramientas de registros o alt+t");
        menuReportes.setEnabled(false);

        itRegis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itRegis.setText("Registro de Movimentos");
        itRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itRegisActionPerformed(evt);
            }
        });
        menuReportes.add(itRegis);

        jMenuBar1.add(menuReportes);

        menuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-support-48.png"))); // NOI18N
        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setToolTipText("Clic para abrir herramientas de registros o alt+t");
        menuMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenimientoActionPerformed(evt);
            }
        });

        itmProductos.setText("Libros");
        itmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmProductosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itmProductos);

        itUsuarios.setText("Usuarios");
        itUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itUsuariosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itUsuarios);

        itDevoluciones.setText("Devoluciones");
        itDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itDevolucionesActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itDevoluciones);

        jMenuBar1.add(menuMantenimiento);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itSalirActionPerformed

    private void itCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCajaActionPerformed
        InterfazPrestamos fCaja = new InterfazPrestamos();
        fCaja.setVisible(true);

    }//GEN-LAST:event_itCajaActionPerformed

    private void itDireProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itDireProActionPerformed
        InterfazAutor fpro = new InterfazAutor();
        fpro.setVisible(true);
    }//GEN-LAST:event_itDireProActionPerformed

    private void itDireClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itDireClieActionPerformed
        InterfazClientes fc = new InterfazClientes();
        fc.setVisible(true);
    }//GEN-LAST:event_itDireClieActionPerformed

    private void itRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itRegisActionPerformed
     Reportes r=new Reportes();
     r.setVisible(true);
    }//GEN-LAST:event_itRegisActionPerformed

    private void menuMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMantenimientoActionPerformed

    private void itmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmProductosActionPerformed
         InterfazLibros fpd = new InterfazLibros();
        fpd.setVisible(true);
    }//GEN-LAST:event_itmProductosActionPerformed

    private void itUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itUsuariosActionPerformed
       InterfazUsuarios fus = new InterfazUsuarios();
       fus.setVisible(true);
    }//GEN-LAST:event_itUsuariosActionPerformed

    private void itDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itDevolucionesActionPerformed
        InterfazDevolucion fcom=new InterfazDevolucion();
        fcom.setVisible(true);
    }//GEN-LAST:event_itDevolucionesActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ventana;
    private javax.swing.JMenuItem itCaja;
    private javax.swing.JMenuItem itDevoluciones;
    private javax.swing.JMenuItem itDireClie;
    private javax.swing.JMenuItem itDirePro;
    private javax.swing.JMenuItem itRegis;
    private javax.swing.JMenuItem itSalir;
    private javax.swing.JMenuItem itUsuarios;
    private javax.swing.JMenuItem itmProductos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables

    
    
}
